### ISSUE TITLE
Links error in README.md

### ISSUE THREAD

**Issue by v-weiyding** [Azure-Samples/functions-quickstart-powershell-azd#4]
1. 
**Describe the issue:**

In the [README.md](https://github.com/Azure-Samples/functions-quickstart-powershell-azd?tab=readme-ov-file#run-your-app-from-the-terminal), when click `testdata.json`, the link leads to a 404 page:

![image](https://github.com/user-attachments/assets/a021cafb-d5ae-4d11-96d3-9365ee65d216)
![image](https://github.com/user-attachments/assets/b20f10c8-ea36-4306-8146-82ec88e85c5a)

**Suggestion:**
Update the link of `testdata.json` to
https://github.com/Azure-Samples/functions-quickstart-powershell-azd/blob/main/src/testdata.json.

2.
**Describe the issue:**

In the [README.md](https://github.com/Azure-Samples/functions-quickstart-powershell-azd?tab=readme-ov-file#run-your-app-from-the-terminal), when click `test.http`, the link leads to a 404 page:

![image](https://github.com/user-attachments/assets/a3f6b03f-5c46-4387-a823-b825ad81af8f)
![image](https://github.com/user-attachments/assets/e044a752-f476-434a-9cca-7199a08f2e99)

**Suggestion:**
Update the link of `test.http` to
https://github.com/Azure-Samples/functions-quickstart-powershell-azd/blob/main/src/test.http.

@hemarina and @BigMorty for notification.

**Comment by BigMorty** [comment]
Fixed by https://github.com/Azure-Samples/functions-quickstart-powershell-azd/pull/5

**Comment by v-weiyding** [comment]
@BigMorty The first issue has been resolved, but the second issue remains unfixed. Please review.

**Comment by BigMorty** [comment]
Sorry for missing that. Fixed by https://github.com/Azure-Samples/functions-quickstart-powershell-azd/pull/6

**Comment by v-weiyding** [comment]
@BigMorty The issue has been fixed, and I will close it.
