### ISSUE TITLE
README tutorial is not working.

### ISSUE THREAD

**Issue by tnovau** [Azure-Samples/functions-quickstart-powershell-azd#8]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Follow README.md, after `azd up` it fails

### Any log messages given by the failure
> 
```
PS /home/tomas/repos/ontheedge/tnovautestazd/src> azd up
? Select an Azure Subscription to use:  1. X
? Select an Azure location to use:  4. (Europe) North Europe (northeurope)

Packaging services (azd package)


Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.

Subscription: X
Location: North Europe

  You can view detailed progress in the Azure Portal:
  https://portal.azure.com/#view/HubsExtension/DeploymentDetailsBlade/~/overview/id/%2Fsubscriptions%2F8b635828-8ea2-4c18-bed6-036c5a60d20f%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Ftnovautestazd-1732115694

  (✓) Done: Resource group: rg-tnovautestazd (1.52s)
  (✓) Done: Virtual Network: vnet-ehyfkyoelktog (3.689s)
  (✓) Done: App Service plan: plan-ehyfkyoelktog (6.568s)
  (✓) Done: Log Analytics workspace: log-ehyfkyoelktog (16.066s)
  (✓) Done: Application Insights: appi-ehyfkyoelktog (2.078s)
  (✓) Done: Storage account: stehyfkyoelktog (23.612s)
  (✓) Done: Private Endpoint: blob-PrivateEndpoint (26.953s)
  (x) Failed: Web App: func-processor-ehyfkyoelktog (31.476s)
  |      =| Creating/Updating resources
ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InternalServerError: There was an unexpected InternalServerError.  Please try again later.  x-ms-correlation-request-id: 94c6ab41684961d3491e71eb9f3e7c3d

TraceID: 94c6ab41684961d3491e71eb9f3e7c3d

```

### Expected/desired behavior
> It works

### OS and Version?
>
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
```

### Versions
> latest (20/11/2024)

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by tnovau** [comment]
I tried with both README.md and this one: https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-azure-developer-cli?pivots=programming-language-powershell&tabs=linux%2Cpost%2Cbash%2Cpowershell

It's failing after `azd up`

![image](https://github.com/user-attachments/assets/584693b7-e400-41b1-a5cd-4f2abfa6a3fe)

**Comment by tnovau** [comment]
It's also not working in windows 10

**Comment by tnovau** [comment]
![image](https://github.com/user-attachments/assets/755ba3e5-b119-4de6-a5cd-26c5744fb5bc)

**Comment by nzthiago** [comment]
Hello @tnovau  - sorry you ran into this issue. The issue is that your subscription doesn't have the Microsoft.App resource provider registered. We are working to make the real error message show up instead of the generic InternalServerError. 

For now, please check if 'Microsoft.App' is registered as a resource provider in your subscription. You may check and register Resource Providers:
* In the Azure Portal. Open the Subscription > Resource Provider tab and find and register the required resource provider. Or
* In Azure Cloud Shell as: `Get-AzResourceProvider -ProviderNamespace Microsoft.App`. 

After that please retry the tutorial, thank you!

**Comment by tnovau** [comment]
Thanks for the guidance, I'm closing it 👍🏼 

Maybe we can put this requirement in the tutorial, what do you think?
